### ISSUE TITLE
How to set the '-n' parameter of hicpro2catch.sh?

### ISSUE THREAD

**Issue by YiweiNiu** [zhanyinx/CaTCH_R#6]
Hi,

Thank you for creating such a useful tool.

If I understand correctly, the `iced.matrix` from HiC-Pro should be used for CaTCH.

Then how to set the `-n` parameter of hicpro2catch.sh?

The default value of `$NORM` is -1, and it would be skipped in line [114 of hicpro2catch.sh](https://github.com/zhanyinx/CaTCH/blob/master/hicpro2catch.sh#L114). I am a little confused.

Sorry if my question is too naive. I am new to Hi-C data analysis.

Thanks in advance.

**Comment by zhanyinx** [comment]
Hi Yiwei,

Thanks for your interest in using CaTCH.
In order to use CaTCH, you cannot pass directly the HiC-Pro output as CaTCH takes as input chromosome-wide maps.

To obtain chromosome wide matrices, I created hicpro2catch.sh which is a bash script allowing to convert the genome wide .matrix file from hic-pro into chromosome wide files. 

hicpro2catch.sh has a keyword argument that allows you to normalize the Hi-C libraries. This option is useful when you want to compare Hi-C maps across experiments, as different sequencing depths might affect follow-up analysis (e.g. differential maps)

The normalization value can be passed through -n keyword argument, e.g.
```bash hicpro2catch.sh -i your_file.matrix -b matrix_binning_size -f bin2coord_file -n NORMALISATION_CONSTANT```

where NORMALISATION_CONSTANT is any value you want to normalize the library

If you don't want to normalize the matrix, for instance because you don't need to make comparisons across libraries, you can ignore the -n keyword argument and no normalization will be performed.

Let me know if this helps
Zhan

**Comment by YiweiNiu** [comment]
Thank you for your quick reply.

> If you don't want to normalize the matrix, for instance because you don't need to make comparisons across libraries, you can ignore the -n keyword argument and no normalization will be performed.

I would like to compare among libraries. Should I use the total number of reads in the matrix as `NORMALISATION_CONSTANT`?

**Comment by zhanyinx** [comment]
You can use the minimum library size across all libraries as normalization constant for all libraries

**Comment by YiweiNiu** [comment]
Got it. Thank you so much.
